version: '3.7'
services:
  backend:
    image: benjiea/backend:v1
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    environment:
    - SECRET_KEY=${SECRET_KEY}
   
  usergen:
    image: benjiea/usergen:v1
    ports:
    - target: 5002  
      published: 5002
      protocol: tcp
    environment:
    - SECRET_KEY=${SECRET_KEY}
  
  housegen:
    image: benjiea/housegen:v1
    ports:
    - target: 5003
      published: 5003
      protocol: tcp
    environment:
    - SECRET_KEY=${SECRET_KEY}   

  frontend:
    image: benjiea/frontend:v1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment:
    - SECRET_KEY=${SECRET_KEY}
    - Version=${Version}
